### ISSUE TITLE
Dependency Missing - ModuleNotFoundError: No module named 'colored'

### ISSUE THREAD

**Issue by opticyclic** [badele/gitcheck#48]
I don't use Python so I installed everything from scratch

    sudo apt install python3-pip
    pip3 install git+git://github.com/badele/gitcheck.git

Now when I run it I get an error: 

    ~/.local/bin/gitcheck
    Traceback (most recent call last):
    File "/home/me/.local/bin/gitcheck", line 5, in <module>
    from gitcheck.gitcheck import main
    File "/home/me/.local/lib/python3.8/site-packages/gitcheck/gitcheck.py", line 23, in <module>
    from colored import fg, bg, attr
    ModuleNotFoundError: No module named 'colored'

Obviously I can do `pip3 install colored` to fix this but you should include it as a dependency so this extra step is not required.

**Comment by opticyclic** [comment]
Duplicate of #33
